'use strict';

window.constants = (function () {
  var LOCATION_X_MIN = 0;
  var LOCATION_X_MAX = 1140;
  var LOCATION_Y_MIN = 130;
  var LOCATION_Y_MAX = 630;
  var PRICE_MAX = 1000000;
  var BUNGALO_PRICE_MIN = 0;
  var FLAT_PRICE_MIN = 1000;
  var HOUSE_PRICE_MIN = 5000;
  var PALACE_PRICE_MIN = 10000;
  var API_URL = 'https://javascript.pages.academy/keksobooking';
  var MAX_PINS_COUNT = 5;
  var MAP_PIN_DEFAULT_TOP = '375px';
  var MAP_PIN_DEFAULT_LEFT = '570px';
  var LOW_PRICE = 10000;
  var HIGH_PRICE = 50000;
  var DEBOUNCE_INTERVAL = 300;
  var FILE_TYPES = ['.gif', '.jpg', '.jpeg', '.png'];
  var AVATAR_DEFAULT = 'img/muffin-grey.svg';

  return {
    LOCATION_X_MIN: LOCATION_X_MIN,
    LOCATION_X_MAX: LOCATION_X_MAX,
    LOCATION_Y_MIN: LOCATION_Y_MIN,
    LOCATION_Y_MAX: LOCATION_Y_MAX,
    PRICE_MAX: PRICE_MAX,
    BUNGALO_PRICE_MIN: BUNGALO_PRICE_MIN,
    FLAT_PRICE_MIN: FLAT_PRICE_MIN,
    HOUSE_PRICE_MIN: HOUSE_PRICE_MIN,
    PALACE_PRICE_MIN: PALACE_PRICE_MIN,
    API_URL: API_URL,
    MAX_PINS_COUNT: MAX_PINS_COUNT,
    MAP_PIN_DEFAULT_TOP: MAP_PIN_DEFAULT_TOP,
    MAP_PIN_DEFAULT_LEFT: MAP_PIN_DEFAULT_LEFT,
    LOW_PRICE: LOW_PRICE,
    HIGH_PRICE: HIGH_PRICE,
    DEBOUNCE_INTERVAL: DEBOUNCE_INTERVAL,
    FILE_TYPES: FILE_TYPES,
    AVATAR_DEFAULT: AVATAR_DEFAULT
  };
})();
